// IATA airline code → operator name mapping (verified)
// Maps to the Chinese bilingual entry where one exists in the operators table.

export const IATA_CODE_MAP: Record<string, string> = {
  // === 中国大陆 ===
  "CA": "中国国际航空 (Air China)",
  "MU": "中国东方航空 (China Eastern)",
  "CZ": "中国南方航空 (China Southern)",
  "HU": "海南航空 (Hainan Airlines)",
  "ZH": "深圳航空 (Shenzhen Airlines)",
  "MF": "厦门航空 (Xiamen Airlines)",
  "3U": "四川航空 (Sichuan Airlines)",
  "SC": "山东航空 (Shandong Airlines)",
  "9C": "春秋航空 (Spring Airlines)",
  "HO": "吉祥航空 (Juneyao Air)",
  "EU": "成都航空 (Chengdu Airlines)",
  "DZ": "东海航空 (Donghai Airlines)",
  "RY": "江西航空",
  "KN": "中国联合航空 (China United Airlines)",
  "FM": "上海航空 (Shanghai Airlines)",
  "GS": "天津航空 (Tianjin Airlines)",
  "PN": "西部航空 (West Air)",
  "OQ": "重庆航空 (Chongqing Airlines)",
  "G5": "华夏航空 (China Express Airlines)",
  "FU": "福州航空 (Fuzhou Airlines)",
  "GX": "北部湾航空 (GX Airlines)",
  "NS": "河北航空 (Hebei Airlines)",
  "BK": "奥凯航空 (Okay Airways)",
  "JR": "幸福航空 (Joy Air)",
  "WH": "China Northwest Airlines (WH)",
  "CN": "Grand China Air",
  "TV": "西藏航空 (Tibet Airlines)",
  "KY": "昆明航空 (Kunming Airlines)",
  "8L": "祥鹏航空 (Lucky Air)",
  "UQ": "乌鲁木齐航空 (Urumqi Air)",
  "9H": "长安航空 (Air Changan)",
  "QW": "青岛航空 (Qingdao Airlines)",
  "DR": "瑞丽航空 (Ruili Airlines)",
  "3Q": "云南航空 (Yunnan Airlines)",
  // === 港澳台 ===
  "CX": "国泰航空 (Cathay Pacific)",
  "KA": "国泰航空 (Cathay Pacific)",
  "CI": "中华航空 (China Airlines)",
  "BR": "长荣航空 (EVA Air)",
  "GE": "TransAsia Airways",
  "B7": "Uni Air",
  // === 日本 ===
  "NH": "全日空 (ANA)",
  "JL": "日本航空 (JAL)",
  "MM": "Peach Aviation",
  "IJ": "Spring Airlines Japan",
  "GK": "Jetstar Japan",
  "EL": "Air Nippon",
  // === 韩国 ===
  "KE": "大韩航空 (Korean Air)",
  "OZ": "韩亚航空 (Asiana Airlines)",
  "LJ": "Jin Air",
  "ZE": "Eastar Jet",
  "TW": "Tway Airlines",
  // === 东南亚 ===
  "SQ": "新加坡航空 (Singapore Airlines)",
  "TG": "泰国国际航空 (Thai Airways)",
  "AK": "亚洲航空 (AirAsia)",
  "VN": "越南航空 (Vietnam Airlines)",
  "TR": "Scoot",
  "FD": "Thai AirAsia",
  "SL": "Thai Lion Air",
  "WE": "Thai Smile Airways",
  "PG": "Bangkok Airways",
  "VJ": "VietJet Air",
  "GA": "Garuda Indonesia",
  "QG": "Citilink Indonesia",
  "IW": "Wings Air",
  "D7": "AirAsia X",
  "XJ": "AirAsia X",
  "FY": "Firefly",
  "OD": "Malindo Air",
  "PR": "Air Philippines",
  "5J": "Cebu Pacific",
  // === 中东 ===
  "EK": "阿联酋航空 (Emirates)",
  "QR": "卡塔尔航空 (Qatar Airways)",
  "TK": "土耳其航空 (Turkish Airlines)",
  "EY": "Etihad Airways",
  "FZ": "Fly Dubai",
  // === 欧洲 ===
  "LH": "汉莎航空 (Lufthansa)",
  "AF": "法国航空 (Air France)",
  "BA": "英国航空 (British Airways)",
  "KL": "荷兰皇家航空 (KLM)",
  "LX": "瑞士国际航空 (SWISS)",
  "AZ": "Alitalia",
  "OS": "Austrian Airlines",
  "SU": "Aeroflot Russian Airlines",
  "U6": "Ural Airlines",
  "UT": "UTair Aviation",
  "DP": "Pobeda",
  "U2": "easyJet",
  "DS": "EasyJet (DS)",
  "VY": "Vueling Airlines",
  "EW": "Eurowings",
  "4U": "Eurowings",
  "X3": "TUIfly (X3)",
  "DE": "Condor Flugdienst",
  "AB": "Air Berlin",
  "TO": "Transavia France",
  "HV": "Transavia Holland",
  "BE": "Flybe",
  "BD": "bmi",
  "WW": "bmibaby",
  "VS": "Virgin Atlantic Airways",
  "BT": "Baltic Airlines",
  "BY": "Thomsonfly",
  // === 北美 ===
  "UA": "美国联合航空 (United Airlines)",
  "DL": "达美航空 (Delta Air Lines)",
  "AA": "美国航空 (American Airlines)",
  "AC": "加拿大航空 (Air Canada)",
  "QK": "Air Canada Jazz",
  "F9": "Frontier Airlines",
  "G4": "Allegiant Air",
  "WS": "WestJet",
  "TS": "Air Transat",
  "WG": "Sunwing",
  // === 大洋洲 ===
  "QF": "澳洲航空 (Qantas)",
  "NZ": "新西兰航空 (Air New Zealand)",
  "VA": "Virgin Australia",
  // === 南亚 ===
  "AI": "Air India Limited",
  "UK": "Air Vistara",
};

// Extract IATA code prefix from a flight number string
// e.g. "NH962" → "NH", "3U8888" → "3U", "CA1234" → "CA"
export function extractIataCode(flightNumber: string): string | null {
  const trimmed = flightNumber.trim().toUpperCase();
  if (!trimmed) return null;
  const match = trimmed.match(/^([A-Z0-9]{1,2})\d/);
  if (!match) return null;
  return match[1];
}
