// ==== OPERATORS ====
export const seedOperators = [
  { name:"中国国家铁路集团有限公司", type:"railway", region:"" },
  { name:"中国铁路北京局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路上海局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路广州局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路成都局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路武汉局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路西安局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路沈阳局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路郑州局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路济南局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路南昌局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路南宁局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路昆明局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路兰州局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路哈尔滨局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路太原局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路呼和浩特局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路乌鲁木齐局集团有限公司", type:"railway", region:"" },
  { name:"中国铁路青藏集团有限公司", type:"railway", region:"" },
  { name:"港铁公司", type:"railway", region:"" },
  { name:"台湾铁路管理局", type:"railway", region:"" },
  { name:"JR东日本", type:"railway", region:"" },
  { name:"JR西日本", type:"railway", region:"" },
  { name:"JR东海", type:"railway", region:"" },
  { name:"JR九州", type:"railway", region:"" },
  { name:"JR北海道", type:"railway", region:"" },
  { name:"韩国铁道公社 (KORAIL)", type:"railway", region:"" },
  { name:"SNCF (法国国家铁路)", type:"railway", region:"" },
  { name:"Deutsche Bahn (德国铁路)", type:"railway", region:"" },
  { name:"Trenitalia (意大利铁路)", type:"railway", region:"" },
  { name:"Renfe (西班牙铁路)", type:"railway", region:"" },
  { name:"Eurostar (欧洲之星)", type:"railway", region:"" },
  { name:"SBB (瑞士联邦铁路)", type:"railway", region:"" },
  { name:"NS (荷兰铁路)", type:"railway", region:"" },
  { name:"Amtrak (美国国铁)", type:"railway", region:"" },
  { name:"VIA Rail Canada", type:"railway", region:"" },
  { name:"俄罗斯铁路 (RZD)", type:"railway", region:"" },
  { name:"中国国际航空 (Air China)", type:"airline", region:"" },
  { name:"中国东方航空 (China Eastern)", type:"airline", region:"" },
  { name:"中国南方航空 (China Southern)", type:"airline", region:"" },
  { name:"海南航空 (Hainan Airlines)", type:"airline", region:"" },
  { name:"深圳航空 (Shenzhen Airlines)", type:"airline", region:"" },
  { name:"厦门航空 (Xiamen Airlines)", type:"airline", region:"" },
  { name:"四川航空 (Sichuan Airlines)", type:"airline", region:"" },
  { name:"山东航空 (Shandong Airlines)", type:"airline", region:"" },
  { name:"春秋航空 (Spring Airlines)", type:"airline", region:"" },
  { name:"吉祥航空 (Juneyao Air)", type:"airline", region:"" },
  { name:"国泰航空 (Cathay Pacific)", type:"airline", region:"" },
  { name:"中华航空 (China Airlines)", type:"airline", region:"" },
  { name:"长荣航空 (EVA Air)", type:"airline", region:"" },
  { name:"全日空 (ANA)", type:"airline", region:"" },
  { name:"日本航空 (JAL)", type:"airline", region:"" },
  { name:"大韩航空 (Korean Air)", type:"airline", region:"" },
  { name:"韩亚航空 (Asiana Airlines)", type:"airline", region:"" },
  { name:"新加坡航空 (Singapore Airlines)", type:"airline", region:"" },
  { name:"泰国国际航空 (Thai Airways)", type:"airline", region:"" },
  { name:"亚洲航空 (AirAsia)", type:"airline", region:"" },
  { name:"越南航空 (Vietnam Airlines)", type:"airline", region:"" },
  { name:"阿联酋航空 (Emirates)", type:"airline", region:"" },
  { name:"卡塔尔航空 (Qatar Airways)", type:"airline", region:"" },
  { name:"土耳其航空 (Turkish Airlines)", type:"airline", region:"" },
  { name:"汉莎航空 (Lufthansa)", type:"airline", region:"" },
  { name:"法国航空 (Air France)", type:"airline", region:"" },
  { name:"英国航空 (British Airways)", type:"airline", region:"" },
  { name:"荷兰皇家航空 (KLM)", type:"airline", region:"" },
  { name:"瑞士国际航空 (SWISS)", type:"airline", region:"" },
  { name:"美国联合航空 (United Airlines)", type:"airline", region:"" },
  { name:"达美航空 (Delta Air Lines)", type:"airline", region:"" },
  { name:"美国航空 (American Airlines)", type:"airline", region:"" },
  { name:"加拿大航空 (Air Canada)", type:"airline", region:"" },
  { name:"澳洲航空 (Qantas)", type:"airline", region:"" },
  { name:"新西兰航空 (Air New Zealand)", type:"airline", region:"" },
  { name:"成都航空", type:"airline", region:"" },
  { name:"东海航空", type:"airline", region:"" },
  { name:"江西航空", type:"airline", region:"" },
  { name:"JR East", type:"railway", region:"日本" },
  { name:"JR West", type:"railway", region:"日本" },
  { name:"JR Central", type:"railway", region:"日本" },
  { name:"Korail", type:"railway", region:"韩国" },
  { name:"SNCF", type:"railway", region:"法国" },
  { name:"Deutsche Bahn", type:"railway", region:"德国" },
  { name:"Trenitalia", type:"railway", region:"意大利" },
  { name:"Amtrak", type:"railway", region:"美国" },
  { name:"Eurostar", type:"railway", region:"英国" },
  { name:"RENFE", type:"railway", region:"西班牙" },
  { name:"SBB CFF FFS", type:"railway", region:"瑞士" },
  { name:"NS", type:"railway", region:"荷兰" },
  { name:"ÖBB", type:"railway", region:"奥地利" },
  { name:"РЖД", type:"railway", region:"俄罗斯" },
  { name:"台灣高鐵", type:"railway", region:"中国台湾" },
  { name:"港鐵 MTR", type:"railway", region:"中国香港" },
  { name:"Air China", type:"airline", region:"China" },
  { name:"China Eastern Airlines", type:"airline", region:"China" },
  { name:"China Southern Airlines", type:"airline", region:"China" },
  { name:"China United Airlines", type:"airline", region:"China" },
  { name:"Yunnan Airlines", type:"airline", region:"China" },
  { name:"Hainan Airlines", type:"airline", region:"China" },
  { name:"Juneyao Airlines", type:"airline", region:"China" },
  { name:"Shandong Airlines", type:"airline", region:"China" },
  { name:"Spring Airlines", type:"airline", region:"China" },
  { name:"Sichuan Airlines", type:"airline", region:"China" },
  { name:"Shanghai Airlines", type:"airline", region:"China" },
  { name:"Shenzhen Airlines", type:"airline", region:"China" },
  { name:"Xiamen Airlines", type:"airline", region:"China" },
  { name:"Tianjin Airlines", type:"airline", region:"China" },
  { name:"China United", type:"airline", region:"China" },
  { name:"Chongqing Airlines", type:"airline", region:"China" },
  { name:"Grand China Air", type:"airline", region:"China" },
  { name:"West Air China", type:"airline", region:"China" },
  { name:"OneChina", type:"airline", region:"China" },
  { name:"Joy Air", type:"airline", region:"China" },
  { name:"Huaxia", type:"airline", region:"China" },
  { name:"China SSS", type:"airline", region:"China" },
  { name:"China Northwest Airlines (WH)", type:"airline", region:"China" },
  { name:"Hebei Airlines", type:"airline", region:"China" },
  { name:"All Asia", type:"airline", region:"China" },
  { name:"Fuzhou Airlines", type:"airline", region:"China" },
  { name:"GX Airlines", type:"airline", region:"China" },
  { name:"40-Mile Air", type:"airline", region:"United States" },
  { name:"Ansett Australia", type:"airline", region:"Australia" },
  { name:"Abacus International", type:"airline", region:"Singapore" },
  { name:"Aigle Azur", type:"airline", region:"France" },
  { name:"Aloha Airlines", type:"airline", region:"United States" },
  { name:"American Airlines", type:"airline", region:"United States" },
  { name:"Allegiant Air", type:"airline", region:"United States" },
  { name:"Air Europa", type:"airline", region:"Spain" },
  { name:"Air Europe", type:"airline", region:"Italy" },
  { name:"Alaska Central Express", type:"airline", region:"United States" },
  { name:"Astraeus", type:"airline", region:"United Kingdom" },
  { name:"Air Italy", type:"airline", region:"Italy" },
  { name:"Alliance Airlines", type:"airline", region:"Australia" },
  { name:"Aeroflot Russian Airlines", type:"airline", region:"Russia" },
  { name:"Air France", type:"airline", region:"France" },
  { name:"Air Caledonie International", type:"airline", region:"France" },
  { name:"Air Cargo Carriers", type:"airline", region:"United States" },
  { name:"Air Glaciers", type:"airline", region:"Switzerland" },
  { name:"Airlift International", type:"airline", region:"United States" },
  { name:"Air Berlin", type:"airline", region:"Germany" },
  { name:"Air India Limited", type:"airline", region:"India" },
  { name:"Air Tahiti Nui", type:"airline", region:"France" },
  { name:"Air One", type:"airline", region:"Italy" },
  { name:"Air Sahara", type:"airline", region:"India" },
  { name:"Air Japan", type:"airline", region:"Japan" },
  { name:"America West Airlines", type:"airline", region:"United States" },
  { name:"Air Wisconsin", type:"airline", region:"United States" },
  { name:"Tatarstan Airlines", type:"airline", region:"Russia" },
  { name:"Allegheny Commuter Airlines", type:"airline", region:"United States" },
  { name:"Air Sunshine", type:"airline", region:"United States" },
  { name:"Air Libert", type:"airline", region:"France" },
  { name:"Air Sicilia", type:"airline", region:"Italy" },
  { name:"ATA Airlines", type:"airline", region:"United States" },
  { name:"All Nippon Airways", type:"airline", region:"Japan" },
  { name:"Air Nostrum", type:"airline", region:"Spain" },
  { name:"Air Arabia", type:"airline", region:"United Arab Emirates" },
  { name:"Air Canada", type:"airline", region:"Canada" },
  { name:"Air Nippon", type:"airline", region:"Japan" },
  { name:"Airnorth", type:"airline", region:"Australia" },
  { name:"Air North Charter - Canada", type:"airline", region:"Canada" },
  { name:"Air New Zealand", type:"airline", region:"New Zealand" },
  { name:"Alitalia Express", type:"airline", region:"Italy" },
  { name:"Aero Flight", type:"airline", region:"Germany" },
  { name:"Arrow Air", type:"airline", region:"United States" },
  { name:"Atlantic Southeast Airlines", type:"airline", region:"United States" },
  { name:"Astrakhan Airlines", type:"airline", region:"Russia" },
  { name:"Airlines Of Tasmania", type:"airline", region:"Australia" },
  { name:"Air Saint Pierre", type:"airline", region:"France" },
  { name:"Austrian Airlines", type:"airline", region:"Austria" },
  { name:"Air Southwest", type:"airline", region:"United Kingdom" },
  { name:"Augsburg Airways", type:"airline", region:"Germany" },
  { name:"Abu Dhabi Amiri Flight", type:"airline", region:"United Arab Emirates" },
  { name:"Aeroflot-Nord", type:"airline", region:"Russia" },
  { name:"Aurigny Air Services", type:"airline", region:"United Kingdom" },
  { name:"Air Mediterranee", type:"airline", region:"France" },
  { name:"Air Moorea", type:"airline", region:"France" },
  { name:"Aeroline GmbH", type:"airline", region:"Germany" },
  { name:"Air Wales", type:"airline", region:"United Kingdom" },
  { name:"Air Caraïbes", type:"airline", region:"France" },
  { name:"Air India Express", type:"airline", region:"India" },
  { name:"Air Exel", type:"airline", region:"Netherlands" },
  { name:"AirAsia", type:"airline", region:"Malaysia" },
  { name:"Atlant-Soyuz Airlines", type:"airline", region:"Russia" },
  { name:"Alitalia", type:"airline", region:"Italy" },
  { name:"Rossiya-Russian Airlines", type:"airline", region:"Russia" },
  { name:"American Eagle Airlines", type:"airline", region:"United States" },
  { name:"AD Aviation", type:"airline", region:"United Kingdom" },
  { name:"Air Foyle", type:"airline", region:"United Kingdom" },
  { name:"Air Chathams", type:"airline", region:"New Zealand" },
  { name:"Access Air", type:"airline", region:"United States" },
  { name:"Adam Air", type:"airline", region:"Indonesia" },
  { name:"Air Dolomiti", type:"airline", region:"Italy" },
  { name:"Aeroflot-Don", type:"airline", region:"Russia" },
  { name:"Air Madrid", type:"airline", region:"Spain" },
  { name:"Air Florida", type:"airline", region:"United States" },
  { name:"Air Philippines", type:"airline", region:"Philippines" },
  { name:"Atlas Air", type:"airline", region:"United States" },
  { name:"Air Canada Jazz", type:"airline", region:"Canada" },
  { name:"Atlasjet", type:"airline", region:"Turkey" },
  { name:"Air Alfa", type:"airline", region:"Turkey" },
  { name:"Air Plus Comet", type:"airline", region:"Spain" },
  { name:"Aeropelican Air Services", type:"airline", region:"Australia" },
  { name:"Air Austral", type:"airline", region:"France" },
  { name:"Asian Spirit", type:"airline", region:"Philippines" },
  { name:"Airlinair", type:"airline", region:"France" },
  { name:"Aircompany Yakutia", type:"airline", region:"Russia" },
  { name:"Arkefly", type:"airline", region:"Netherlands" },
  { name:"AirTran Airways", type:"airline", region:"United States" },
  { name:"Air Transat", type:"airline", region:"Canada" },
  { name:"Tyrolean Airways", type:"airline", region:"Austria" },
  { name:"Alrosa Mirny Air Enterprise", type:"airline", region:"Russia" },
  { name:"British Airways", type:"airline", region:"United Kingdom" },
  { name:"Belair Airlines", type:"airline", region:"Switzerland" },
  { name:"British International Helicopters", type:"airline", region:"United Kingdom" },
  { name:"Bangkok Airways", type:"airline", region:"Thailand" },
  { name:"Baltic Airlines", type:"airline", region:"Russia" },
  { name:"Bearskin Lake Air Service", type:"airline", region:"Canada" },
  { name:"bmi", type:"airline", region:"United Kingdom" },
  { name:"bmibaby", type:"airline", region:"United Kingdom" },
  { name:"Bemidji Airlines", type:"airline", region:"United States" },
  { name:"British Midland Regional", type:"airline", region:"United Kingdom" },
  { name:"Blue Panorama Airlines", type:"airline", region:"Italy" },
  { name:"Bering Air", type:"airline", region:"United States" },
  { name:"Metro Batavia", type:"airline", region:"Indonesia" },
  { name:"Berjaya Air", type:"airline", region:"Malaysia" },
  { name:"Blue Wings", type:"airline", region:"Germany" },
  { name:"Brit Air", type:"airline", region:"France" },
  { name:"Binter Canarias", type:"airline", region:"Spain" },
  { name:"British Mediterranean Airways", type:"airline", region:"United Kingdom" },
  { name:"Calima Aviacion", type:"airline", region:"Spain" },
  { name:"Canadian Airlines", type:"airline", region:"Canada" },
  { name:"Canadian North", type:"airline", region:"Canada" },
  { name:"Cape Air", type:"airline", region:"United States" },
  { name:"Cebu Pacific", type:"airline", region:"Philippines" },
  { name:"Charter Air", type:"airline", region:"Austria" },
  { name:"Chautauqua Airlines", type:"airline", region:"United States" },
  { name:"China Airlines", type:"airline", region:"Taiwan" },
  { name:"Cirrus Airlines", type:"airline", region:"Germany" },
  { name:"BA CityFlyer", type:"airline", region:"United Kingdom" },
  { name:"Coastal Air", type:"airline", region:"United States" },
  { name:"Colgan Air", type:"airline", region:"United States" },
  { name:"Comair", type:"airline", region:"United States" },
  { name:"CommutAir", type:"airline", region:"United States" },
  { name:"Compass Airlines", type:"airline", region:"United States" },
  { name:"Condor Flugdienst", type:"airline", region:"Germany" },
  { name:"Contact Air", type:"airline", region:"Germany" },
  { name:"Continental Airlines", type:"airline", region:"United States" },
  { name:"Continental Express", type:"airline", region:"United States" },
  { name:"Continental Micronesia", type:"airline", region:"United States" },
  { name:"Corendon Airlines", type:"airline", region:"Turkey" },
  { name:"Corsairfly", type:"airline", region:"France" },
  { name:"Corse-Mediterranee", type:"airline", region:"France" },
  { name:"Crest Aviation", type:"airline", region:"United Kingdom" },
  { name:"Crown Airways", type:"airline", region:"United States" },
  { name:"Cyprus Turkish Airlines", type:"airline", region:"Turkey" },
  { name:"Dalavia", type:"airline", region:"Russia" },
  { name:"Darwin Airline", type:"airline", region:"Switzerland" },
  { name:"Delta Aerotaxi", type:"airline", region:"Italy" },
  { name:"Delta Air Lines", type:"airline", region:"United States" },
  { name:"Denim Air", type:"airline", region:"Netherlands" },
  { name:"Domodedovo Airlines", type:"airline", region:"Russia" },
  { name:"dba", type:"airline", region:"Germany" },
  { name:"EVA Air", type:"airline", region:"Taiwan" },
  { name:"Eastern Airways", type:"airline", region:"United Kingdom" },
  { name:"Eastland Air", type:"airline", region:"Australia" },
  { name:"Edelweiss Air", type:"airline", region:"Switzerland" },
  { name:"Emirates", type:"airline", region:"United Arab Emirates" },
  { name:"Etihad Airways", type:"airline", region:"United Arab Emirates" },
  { name:"Eurofly Service", type:"airline", region:"Italy" },
  { name:"European Air Express", type:"airline", region:"Germany" },
  { name:"Eurowings", type:"airline", region:"Germany" },
  { name:"Evergreen International Airlines", type:"airline", region:"United States" },
  { name:"Excel Airways", type:"airline", region:"United Kingdom" },
  { name:"Excel Charter", type:"airline", region:"United Kingdom" },
  { name:"Express One International", type:"airline", region:"United States" },
  { name:"ExpressJet", type:"airline", region:"United States" },
  { name:"easyJet", type:"airline", region:"United Kingdom" },
  { name:"Far Eastern Air Transport", type:"airline", region:"Taiwan" },
  { name:"Firefly", type:"airline", region:"Malaysia" },
  { name:"First Air", type:"airline", region:"Canada" },
  { name:"First Choice Airways", type:"airline", region:"United Kingdom" },
  { name:"Flightline", type:"airline", region:"United Kingdom" },
  { name:"Florida West International Airways", type:"airline", region:"United States" },
  { name:"AirAsia X", type:"airline", region:"Malaysia" },
  { name:"Flybaboo", type:"airline", region:"Switzerland" },
  { name:"Flybe", type:"airline", region:"United Kingdom" },
  { name:"Flyglobespan", type:"airline", region:"United Kingdom" },
  { name:"Flyhy Cargo Airlines", type:"airline", region:"Thailand" },
  { name:"Formosa Airlines", type:"airline", region:"Taiwan" },
  { name:"Freedom Air", type:"airline", region:"United States" },
  { name:"Freedom Airlines", type:"airline", region:"United States" },
  { name:"Frontier Airlines", type:"airline", region:"United States" },
  { name:"Frontier Flying Service", type:"airline", region:"United States" },
  { name:"GB Airways", type:"airline", region:"United Kingdom" },
  { name:"Garuda Indonesia", type:"airline", region:"Indonesia" },
  { name:"Gazpromavia", type:"airline", region:"Russia" },
  { name:"Germania", type:"airline", region:"Germany" },
  { name:"Germanwings", type:"airline", region:"Germany" },
  { name:"Go Air", type:"airline", region:"India" },
  { name:"GoJet Airlines", type:"airline", region:"United States" },
  { name:"Great Lakes Airlines", type:"airline", region:"United States" },
  { name:"Gulfstream International Airlines", type:"airline", region:"United States" },
  { name:"Hageland Aviation Services", type:"airline", region:"United States" },
  { name:"Hamburg International", type:"airline", region:"Germany" },
  { name:"TUIfly", type:"airline", region:"Germany" },
  { name:"Hapagfly", type:"airline", region:"Germany" },
  { name:"Hawaiian Airlines", type:"airline", region:"United States" },
  { name:"Hawkair", type:"airline", region:"Canada" },
  { name:"Heli France", type:"airline", region:"France" },
  { name:"Helijet", type:"airline", region:"Canada" },
  { name:"Hello", type:"airline", region:"Switzerland" },
  { name:"Helvetic Airways", type:"airline", region:"Switzerland" },
  { name:"Hex'Air", type:"airline", region:"France" },
  { name:"Highland Airways", type:"airline", region:"United Kingdom" },
  { name:"Hokkaido International Airlines", type:"airline", region:"Japan" },
  { name:"Horizon Air", type:"airline", region:"United States" },
  { name:"Horizon Airlines", type:"airline", region:"Australia" },
  { name:"Iberia Airlines", type:"airline", region:"Spain" },
  { name:"Iberworld", type:"airline", region:"Spain" },
  { name:"Ibex Airlines", type:"airline", region:"Japan" },
  { name:"IndiGo Airlines", type:"airline", region:"India" },
  { name:"Indian Airlines", type:"airline", region:"India" },
  { name:"Indigo", type:"airline", region:"United States" },
  { name:"Indonesia AirAsia", type:"airline", region:"Indonesia" },
  { name:"Indonesian Airlines", type:"airline", region:"Indonesia" },
  { name:"Interavia Airlines", type:"airline", region:"Russia" },
  { name:"Intersky", type:"airline", region:"Austria" },
  { name:"Island Airlines", type:"airline", region:"United States" },
  { name:"Cargo Plus Aviation", type:"airline", region:"United Arab Emirates" },
  { name:"Islas Airways", type:"airline", region:"Spain" },
  { name:"JAL Express", type:"airline", region:"Japan" },
  { name:"JALways", type:"airline", region:"Japan" },
  { name:"Japan Airlines", type:"airline", region:"Japan" },
  { name:"Japan Airlines Domestic", type:"airline", region:"Japan" },
  { name:"Japan Asia Airways", type:"airline", region:"Japan" },
  { name:"Japan Transocean Air", type:"airline", region:"Japan" },
  { name:"Jet Airways", type:"airline", region:"India" },
  { name:"Jetstar Asia Airways", type:"airline", region:"Singapore" },
  { name:"Jet2.com", type:"airline", region:"United Kingdom" },
  { name:"JetBlue Airways", type:"airline", region:"United States" },
  { name:"Jetstar Airways", type:"airline", region:"Australia" },
  { name:"KD Avia", type:"airline", region:"Russia" },
  { name:"KLM Cityhopper", type:"airline", region:"Netherlands" },
  { name:"KLM Royal Dutch Airlines", type:"airline", region:"Netherlands" },
  { name:"Kavminvodyavia", type:"airline", region:"Russia" },
  { name:"Kendell Airlines", type:"airline", region:"Australia" },
  { name:"Kenmore Air", type:"airline", region:"United States" },
  { name:"Kingfisher Airlines", type:"airline", region:"India" },
  { name:"Kogalymavia Air Company", type:"airline", region:"Russia" },
  { name:"Kosmos", type:"airline", region:"Russia" },
  { name:"Krasnojarsky Airlines", type:"airline", region:"Russia" },
  { name:"Kuban Airlines", type:"airline", region:"Russia" },
  { name:"Kuzu Airlines Cargo", type:"airline", region:"Turkey" },
  { name:"LTE International Airways", type:"airline", region:"Spain" },
  { name:"LTU Austria", type:"airline", region:"Austria" },
  { name:"Lauda Air", type:"airline", region:"Austria" },
  { name:"Lion Mentari Airlines", type:"airline", region:"Indonesia" },
  { name:"Luftfahrtgesellschaft Walter", type:"airline", region:"Germany" },
  { name:"Lufthansa", type:"airline", region:"Germany" },
  { name:"Lufthansa Cargo", type:"airline", region:"Germany" },
  { name:"Lufthansa CityLine", type:"airline", region:"Germany" },
  { name:"MNG Airlines", type:"airline", region:"Turkey" },
  { name:"Macair Airlines", type:"airline", region:"Australia" },
  { name:"Malaysia Airlines", type:"airline", region:"Malaysia" },
  { name:"Mandala Airlines", type:"airline", region:"Indonesia" },
  { name:"Mandarin Airlines", type:"airline", region:"Taiwan" },
  { name:"Martinair", type:"airline", region:"Netherlands" },
  { name:"Meridiana", type:"airline", region:"Italy" },
  { name:"Merpati Nusantara Airlines", type:"airline", region:"Indonesia" },
  { name:"Mesa Airlines", type:"airline", region:"United States" },
  { name:"Mesaba Airlines", type:"airline", region:"United States" },
  { name:"Midway Airlines", type:"airline", region:"United States" },
  { name:"Midwest Airlines", type:"airline", region:"United States" },
  { name:"Monarch Airlines", type:"airline", region:"United Kingdom" },
  { name:"Myway Airlines", type:"airline", region:"Italy" },
  { name:"Morningstar Air Express", type:"airline", region:"Canada" },
  { name:"Moskovia Airlines", type:"airline", region:"Russia" },
  { name:"MyTravel Airways", type:"airline", region:"United Kingdom" },
  { name:"National Jet Systems", type:"airline", region:"Australia" },
  { name:"NetJets", type:"airline", region:"United States" },
  { name:"New England Airlines", type:"airline", region:"United States" },
  { name:"Niki", type:"airline", region:"Austria" },
  { name:"Nok Air", type:"airline", region:"Thailand" },
  { name:"Norfolk County Flight College", type:"airline", region:"United Kingdom" },
  { name:"North American Airlines", type:"airline", region:"Canada" },
  { name:"North American Charters", type:"airline", region:"Canada" },
  { name:"Northern Dene Airways", type:"airline", region:"Canada" },
  { name:"Northwest Airlines", type:"airline", region:"United States" },
  { name:"Northwestern Air", type:"airline", region:"Canada" },
  { name:"Oasis Hong Kong Airlines", type:"airline", region:"Hong Kong" },
  { name:"Omni Air International", type:"airline", region:"United States" },
  { name:"One Two Go Airlines", type:"airline", region:"Thailand" },
  { name:"Onur Air", type:"airline", region:"Turkey" },
  { name:"Orenburg Airlines", type:"airline", region:"Russia" },
  { name:"Orient Thai Airlines", type:"airline", region:"Thailand" },
  { name:"Origin Pacific Airways", type:"airline", region:"New Zealand" },
  { name:"Ostfriesische Lufttransport", type:"airline", region:"Germany" },
  { name:"Ozjet Airlines", type:"airline", region:"Australia" },
  { name:"PAN Air", type:"airline", region:"Spain" },
  { name:"PB Air", type:"airline", region:"Thailand" },
  { name:"Jetstar Pacific", type:"airline", region:"Vietnam" },
  { name:"Pacific Coastal Airline", type:"airline", region:"Canada" },
  { name:"Pacific East Asia Cargo Airlines", type:"airline", region:"Philippines" },
  { name:"Pacific Island Aviation", type:"airline", region:"United States" },
  { name:"Pacific Wings", type:"airline", region:"United States" },
  { name:"Paramount Airways", type:"airline", region:"India" },
  { name:"Pegasus Airlines", type:"airline", region:"Turkey" },
  { name:"Peninsula Airways", type:"airline", region:"United States" },
  { name:"Philippine Airlines", type:"airline", region:"Philippines" },
  { name:"Piedmont Airlines (1948-1989)", type:"airline", region:"United States" },
  { name:"Pinnacle Airlines", type:"airline", region:"United States" },
  { name:"Polet", type:"airline", region:"Russia" },
  { name:"Porter Airlines", type:"airline", region:"Canada" },
  { name:"Potomac Air", type:"airline", region:"United States" },
  { name:"Privatair", type:"airline", region:"Switzerland" },
  { name:"Qantas", type:"airline", region:"Australia" },
  { name:"Qatar Airways", type:"airline", region:"Qatar" },
  { name:"Kinloss Flying Training Unit", type:"airline", region:"United Kingdom" },
  { name:"Regional Express", type:"airline", region:"Australia" },
  { name:"Republic Airlines", type:"airline", region:"United States" },
  { name:"Republic Express Airlines", type:"airline", region:"Indonesia" },
  { name:"Rossiya", type:"airline", region:"Russia" },
  { name:"Rusline", type:"airline", region:"Russia" },
  { name:"Ryan Air Services", type:"airline", region:"United States" },
  { name:"Ryan International Airlines", type:"airline", region:"United States" },
  { name:"Régional", type:"airline", region:"France" },
  { name:"ScotAirways", type:"airline", region:"United Kingdom" },
  { name:"S7 Airlines", type:"airline", region:"Russia" },
  { name:"Seaborne Airlines", type:"airline", region:"United States" },
  { name:"Scenic Airlines", type:"airline", region:"United States" },
  { name:"Sun Country Airlines", type:"airline", region:"United States" },
  { name:"Southeast Air", type:"airline", region:"United States" },
  { name:"Spicejet", type:"airline", region:"India" },
  { name:"Star Flyer", type:"airline", region:"Japan" },
  { name:"Skagway Air Service", type:"airline", region:"United States" },
  { name:"Singapore Airlines", type:"airline", region:"Singapore" },
  { name:"Sibaviatrans", type:"airline", region:"Russia" },
  { name:"Sriwijaya Air", type:"airline", region:"Indonesia" },
  { name:"Singapore Airlines Cargo", type:"airline", region:"Singapore" },
  { name:"South East Asian Airlines", type:"airline", region:"Philippines" },
  { name:"Skyservice Airlines", type:"airline", region:"Canada" },
  { name:"Southwest Airlines", type:"airline", region:"United States" },
  { name:"Swiss International Air Lines", type:"airline", region:"Switzerland" },
  { name:"Swissair", type:"airline", region:"Switzerland" },
  { name:"Swiss European Air Lines", type:"airline", region:"Switzerland" },
  { name:"SunExpress", type:"airline", region:"Turkey" },
  { name:"Skywalk Airlines", type:"airline", region:"United States" },
  { name:"Spanair", type:"airline", region:"Spain" },
  { name:"Spirit Airlines", type:"airline", region:"United States" },
  { name:"Skywest Airlines", type:"airline", region:"Australia" },
  { name:"SkyWest", type:"airline", region:"United States" },
  { name:"Skymark Airlines", type:"airline", region:"Japan" },
  { name:"SilkAir", type:"airline", region:"Singapore" },
  { name:"Skynet Asia Airways", type:"airline", region:"Japan" },
  { name:"Southern Airways", type:"airline", region:"United States" },
  { name:"Saratov Aviation Division", type:"airline", region:"Russia" },
  { name:"South Pacific Island Airways", type:"airline", region:"United States" },
  { name:"Shuttle America", type:"airline", region:"United States" },
  { name:"Thai Air Cargo", type:"airline", region:"Thailand" },
  { name:"Thomas Cook Airlines", type:"airline", region:"United Kingdom" },
  { name:"Trigana Air Service", type:"airline", region:"Indonesia" },
  { name:"Tiger Airways", type:"airline", region:"Singapore" },
  { name:"Tiger Airways Australia", type:"airline", region:"Australia" },
  { name:"Thai Airways International", type:"airline", region:"Thailand" },
  { name:"Turk Hava Kurumu Hava Taksi Isletmesi", type:"airline", region:"Turkey" },
  { name:"Thai AirAsia", type:"airline", region:"Thailand" },
  { name:"Turkish Airlines", type:"airline", region:"Turkey" },
  { name:"Twin Jet", type:"airline", region:"France" },
  { name:"Thomsonfly", type:"airline", region:"United Kingdom" },
  { name:"TransAsia Airways", type:"airline", region:"Taiwan" },
  { name:"Transavia Holland", type:"airline", region:"Netherlands" },
  { name:"Transwest Air", type:"airline", region:"Canada" },
  { name:"Transaero Airlines", type:"airline", region:"Russia" },
  { name:"Turkish Air Force", type:"airline", region:"Turkey" },
  { name:"Trans States Airlines", type:"airline", region:"United States" },
  { name:"USA3000 Airlines", type:"airline", region:"United States" },
  { name:"United Airlines", type:"airline", region:"United States" },
  { name:"Ural Airlines", type:"airline", region:"Russia" },
  { name:"US Airways", type:"airline", region:"United States" },
  { name:"US Helicopter", type:"airline", region:"United States" },
  { name:"UTair Aviation", type:"airline", region:"Russia" },
  { name:"United States Air Force", type:"airline", region:"United States" },
  { name:"US Helicopter Corporation", type:"airline", region:"United States" },
  { name:"Valuair", type:"airline", region:"Singapore" },
  { name:"Vasco Air", type:"airline", region:"Vietnam" },
  { name:"Vietnam Airlines", type:"airline", region:"Vietnam" },
  { name:"VIM Airlines", type:"airline", region:"Russia" },
  { name:"Volga-Dnepr Airlines", type:"airline", region:"Russia" },
  { name:"Virgin America", type:"airline", region:"United States" },
  { name:"Virgin Atlantic Airways", type:"airline", region:"United Kingdom" },
  { name:"Volare Airlines", type:"airline", region:"Italy" },
  { name:"Vueling Airlines", type:"airline", region:"Spain" },
  { name:"Vladivostok Air", type:"airline", region:"Russia" },
  { name:"Virgin Australia", type:"airline", region:"Australia" },
  { name:"Welcome Air", type:"airline", region:"Austria" },
  { name:"West Coast Air", type:"airline", region:"Canada" },
  { name:"WestJet", type:"airline", region:"Canada" },
  { name:"Western Airlines", type:"airline", region:"United States" },
  { name:"Wind Jet", type:"airline", region:"Italy" },
  { name:"Wings Air", type:"airline", region:"Indonesia" },
  { name:"World Airways", type:"airline", region:"United States" },
  { name:"XL Airways France", type:"airline", region:"France" },
  { name:"Yamal Airlines", type:"airline", region:"Russia" },
  { name:"Zoom Airlines", type:"airline", region:"Canada" },
  { name:"Sky Express", type:"airline", region:"Russia" },
  { name:"Globus", type:"airline", region:"Russia" },
  { name:"Japan Air System", type:"airline", region:"Japan" },
  { name:"EasyJet (DS)", type:"airline", region:"Switzerland" },
  { name:"Carnival Air Lines", type:"airline", region:"United States" },
  { name:"Transavia France", type:"airline", region:"France" },
  { name:"Island Air (WP)", type:"airline", region:"United States" },
  { name:"Uni Air", type:"airline", region:"Taiwan" },
  { name:"Red Wings", type:"airline", region:"Russia" },
  { name:"TUIfly (X3)", type:"airline", region:"Germany" },
  { name:"Kostromskie avialinii", type:"airline", region:"Russia" },
  { name:"Greenfly", type:"airline", region:"Spain" },
  { name:"Zest Air", type:"airline", region:"Philippines" },
  { name:"Eastar Jet", type:"airline", region:"South Korea" },
  { name:"Jin Air", type:"airline", region:"South Korea" },
  { name:"Ciel Canadien", type:"airline", region:"Canada" },
  { name:"Canadian National Airways", type:"airline", region:"Canada" },
  { name:"Epic Holiday", type:"airline", region:"United States" },
  { name:"Indochina Airlines", type:"airline", region:"Vietnam" },
  { name:"German Air Force - FLB", type:"airline", region:"Germany" },
  { name:"Line Blue", type:"airline", region:"Germany" },
  { name:"Salzburg arrows", type:"airline", region:"Austria" },
  { name:"Texas Wings", type:"airline", region:"United States" },
  { name:"Atifly", type:"airline", region:"United States" },
  { name:"Ciao Air", type:"airline", region:"Italy" },
  { name:"Jc royal.britannica", type:"airline", region:"United Kingdom" },
  { name:"CanXpress", type:"airline", region:"Canada" },
  { name:"Sharp Airlines", type:"airline", region:"Australia" },
  { name:"CanXplorer", type:"airline", region:"Canada" },
  { name:"World Experience Airline", type:"airline", region:"Canada" },
  { name:"ALAK", type:"airline", region:"Russia" },
  { name:"Air Choice One", type:"airline", region:"United States" },
  { name:"Locair", type:"airline", region:"United States" },
  { name:"SeaPort Airlines", type:"airline", region:"United States" },
  { name:"Salmon Air", type:"airline", region:"United States" },
  { name:"Bobb Air Freight", type:"airline", region:"Germany" },
  { name:"Pelita", type:"airline", region:"Indonesia" },
  { name:"Alaska Seaplane Service", type:"airline", region:"United States" },
  { name:"Enerjet", type:"airline", region:"Canada" },
  { name:"Polar Airlines", type:"airline", region:"Russia" },
  { name:"Andalus Lineas Aereas", type:"airline", region:"Spain" },
  { name:"Amsterdam Airlines", type:"airline", region:"Netherlands" },
  { name:"Air Volga", type:"airline", region:"Russia" },
  { name:"Turkuaz Airlines", type:"airline", region:"Turkey" },
  { name:"Gryphon Airlines", type:"airline", region:"United States" },
  { name:"Gadair European Airlines", type:"airline", region:"Spain" },
  { name:"Spirit of Manila Airlines", type:"airline", region:"Philippines" },
  { name:"QatXpress", type:"airline", region:"Qatar" },
  { name:"NordStar Airlines", type:"airline", region:"Russia" },
  { name:"Air India Regional", type:"airline", region:"India" },
  { name:"MDLR Airlines", type:"airline", region:"India" },
  { name:"Jagson Airlines", type:"airline", region:"India" },
  { name:"Xpressair", type:"airline", region:"Indonesia" },
  { name:"Strategic Airlines", type:"airline", region:"Australia" },
  { name:"Jupiter Airlines", type:"airline", region:"United Arab Emirates" },
  { name:"Fuji Dream Airlines", type:"airline", region:"Japan" },
  { name:"Korea Express Air", type:"airline", region:"South Korea" },
  { name:"SGA Airlines", type:"airline", region:"Thailand" },
  { name:"Air2there", type:"airline", region:"New Zealand" },
  { name:"Avianova (Russia)", type:"airline", region:"Russia" },
  { name:"EuropeSky", type:"airline", region:"Germany" },
  { name:"Homer Air", type:"airline", region:"Germany" },
  { name:"U.S. Air", type:"airline", region:"United States" },
  { name:"Jayrow", type:"airline", region:"Australia" },
  { name:"Wilderness Air", type:"airline", region:"Australia" },
  { name:"Whitaker Air", type:"airline", region:"Australia" },
  { name:"PanAm World Airways", type:"airline", region:"United States" },
  { name:"Virginwings", type:"airline", region:"Germany" },
  { name:"SOCHI AIR", type:"airline", region:"Russia" },
  { name:"LCM AIRLINES", type:"airline", region:"Russia" },
  { name:"Royal European Airlines", type:"airline", region:"United Kingdom" },
  { name:"Tom\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'s & co airliners", type:"airline", region:"France" },
  { name:"LSM Airlines", type:"airline", region:"Russia" },
  { name:"Zapolyarie Airlines", type:"airline", region:"Russia" },
  { name:"Fly Dubai", type:"airline", region:"United Arab Emirates" },
  { name:"ConneX European Airline", type:"airline", region:"Austria" },
  { name:"Aereonautica militare", type:"airline", region:"Italy" },
  { name:"Kal Star Aviation", type:"airline", region:"Indonesia" },
  { name:"LSM AIRLINES", type:"airline", region:"Russia" },
  { name:"UTair-Express", type:"airline", region:"Russia" },
  { name:"Zabaykalskii Airlines", type:"airline", region:"Russia" },
  { name:"CBM America", type:"airline", region:"United States" },
  { name:"Marysya Airlines", type:"airline", region:"Russia" },
  { name:"Westfalia Express VA", type:"airline", region:"Germany" },
  { name:"Black Stallion Airways", type:"airline", region:"United States" },
  { name:"German International Air Lines", type:"airline", region:"Germany" },
  { name:"AIR INDOCHINE", type:"airline", region:"Vietnam" },
  { name:"Happy Air", type:"airline", region:"Thailand" },
  { name:"Solar Air", type:"airline", region:"Thailand" },
  { name:"Air Mekong", type:"airline", region:"Vietnam" },
  { name:"Harbour Air (Priv)", type:"airline", region:"Canada" },
  { name:"Air Hamburg (AHO)", type:"airline", region:"Germany" },
  { name:"ZABAIKAL AIRLINES", type:"airline", region:"Russia" },
  { name:"Yellowstone Club Private Shuttle", type:"airline", region:"United States" },
  { name:"CB Airways UK ( Interliging Flights )", type:"airline", region:"United Kingdom" },
  { name:"Trans Pas Air", type:"airline", region:"United States" },
  { name:"KMV", type:"airline", region:"Russia" },
  { name:"Indya Airline Group", type:"airline", region:"India" },
  { name:"Sunwing", type:"airline", region:"Canada" },
  { name:"Turkish Wings Domestic", type:"airline", region:"Turkey" },
  { name:"Japan Regio", type:"airline", region:"Japan" },
  { name:"OCEAN AIR CARGO", type:"airline", region:"India" },
  { name:"PEGASUS AIRLINES-", type:"airline", region:"Turkey" },
  { name:"Sky Regional", type:"airline", region:"Canada" },
  { name:"LSM International", type:"airline", region:"Russia" },
  { name:"Luchsh Airlines", type:"airline", region:"Russia" },
  { name:"Air Cargo Germany", type:"airline", region:"Germany" },
  { name:"Tway Airlines", type:"airline", region:"South Korea" },
  { name:"Papillon Grand Canyon Helicopters", type:"airline", region:"United States" },
  { name:"AeroWorld", type:"airline", region:"Russia" },
  { name:"Usa Sky Cargo", type:"airline", region:"United States" },
  { name:"Hankook Airline", type:"airline", region:"South Korea" },
  { name:"Red Jet Canada", type:"airline", region:"Canada" },
  { name:"Marusya Airways", type:"airline", region:"Russia" },
  { name:"Era Alaska", type:"airline", region:"United States" },
  { name:"AirRussia", type:"airline", region:"Russia" },
  { name:"Hankook Air US", type:"airline", region:"United States" },
  { name:"I-Fly", type:"airline", region:"Russia" },
  { name:"VickJet", type:"airline", region:"France" },
  { name:"Hamburg Airways", type:"airline", region:"Germany" },
  { name:"Kan Air", type:"airline", region:"Thailand" },
  { name:"Air Cudlua", type:"airline", region:"United Kingdom" },
  { name:"Polet Airlines (Priv)", type:"airline", region:"Russia" },
  { name:"12 North", type:"airline", region:"India" },
  { name:"Comtel Air", type:"airline", region:"Austria" },
  { name:"Mint Airways", type:"airline", region:"Spain" },
  { name:"Orbit Airlines", type:"airline", region:"United States" },
  { name:"AlbaStar", type:"airline", region:"Spain" },
  { name:"Eagles Airlines", type:"airline", region:"Italy" },
  { name:"Alitalia Cityliner", type:"airline", region:"Italy" },
  { name:"Orchid Airlines", type:"airline", region:"Australia" },
  { name:"Skywest Australia", type:"airline", region:"Australia" },
  { name:"BusinessAir", type:"airline", region:"Thailand" },
  { name:"SENIC AIRLINES", type:"airline", region:"United States" },
  { name:"XOJET", type:"airline", region:"United States" },
  { name:"Sky Wing Pacific", type:"airline", region:"South Korea" },
  { name:"Orbit International Airlines", type:"airline", region:"United States" },
  { name:"Orbit Regional Airlines", type:"airline", region:"United States" },
  { name:"Orbit Atlantic Airways", type:"airline", region:"United States" },
  { name:"Volotea", type:"airline", region:"Spain" },
  { name:"Peach Aviation", type:"airline", region:"Japan" },
  { name:"Helitt Líneas Aéreas", type:"airline", region:"Spain" },
  { name:"Russia State Transport", type:"airline", region:"Russia" },
  { name:"Malaysia Wings", type:"airline", region:"Malaysia" },
  { name:"Aviabus", type:"airline", region:"Russia" },
  { name:"Indonesia Sky", type:"airline", region:"Indonesia" },
  { name:"Aws express", type:"airline", region:"United States" },
  { name:"Southjet", type:"airline", region:"United States" },
  { name:"Southjet connect", type:"airline", region:"United States" },
  { name:"Southjet cargo", type:"airline", region:"United States" },
  { name:"Iberia Express", type:"airline", region:"Spain" },
  { name:"Scoot", type:"airline", region:"Singapore" },
  { name:"Zenith International Airline", type:"airline", region:"Thailand" },
  { name:"Air Alps Aviation (A6)", type:"airline", region:"Austria" },
  { name:"Flying kangaroo Airline", type:"airline", region:"Australia" },
  { name:"RusJet", type:"airline", region:"Russia" },
  { name:"VietJet Air", type:"airline", region:"Vietnam" },
  { name:"Patriot Airways", type:"airline", region:"United States" },
  { name:"Vision Airlines (V2)", type:"airline", region:"United States" },
  { name:"AirAsia Japan", type:"airline", region:"Japan" },
  { name:"Yellowtail", type:"airline", region:"United States" },
  { name:"Royal Airways", type:"airline", region:"United States" },
  { name:"Executive AirShare", type:"airline", region:"United States" },
  { name:"T.J. Air", type:"airline", region:"United States" },
  { name:"SkyWork Airlines", type:"airline", region:"Switzerland" },
  { name:"Maastricht Airlines", type:"airline", region:"Netherlands" },
  { name:"Euro Jet", type:"airline", region:"Germany" },
  { name:"Rotana Jet", type:"airline", region:"United Arab Emirates" },
  { name:"SOCHI AIR CHATER", type:"airline", region:"Russia" },
  { name:"Malindo Air", type:"airline", region:"Malaysia" },
  { name:"IzAvia", type:"airline", region:"Russia" },
  { name:"Катэкавиа", type:"airline", region:"Russia" },
  { name:"Псковавиа", type:"airline", region:"Russia" },
  { name:"Maryland Air", type:"airline", region:"United States" },
  { name:"Apache Air", type:"airline", region:"United States" },
  { name:"MHS Aviation GmbH", type:"airline", region:"Germany" },
  { name:"Jettor Airlines", type:"airline", region:"Hong Kong" },
  { name:"Thai Lion Air", type:"airline", region:"Thailand" },
  { name:"Canaryfly", type:"airline", region:"Spain" },
  { name:"National Air Cargo", type:"airline", region:"United States" },
  { name:"Eastern Atlantic Virtual Airlines", type:"airline", region:"United States" },
  { name:"Citilink Indonesia", type:"airline", region:"Indonesia" },
  { name:"Transair", type:"airline", region:"Canada" },
  { name:"Comfort Express Virtual Charters Albany", type:"airline", region:"United States" },
  { name:"Comfort Express Virtual Charters", type:"airline", region:"United States" },
  { name:"Russkie Krylya", type:"airline", region:"Russia" },
  { name:"XAIR USA", type:"airline", region:"United States" },
  { name:"Air Costa", type:"airline", region:"India" },
  { name:"Royal Flight", type:"airline", region:"Russia" },
  { name:"BBN-Airways", type:"airline", region:"United Kingdom" },
  { name:"Tomsk-Avia", type:"airline", region:"Russia" },
  { name:"Avilu", type:"airline", region:"Switzerland" },
  { name:"Skyline Ulasim Ticaret A.S.", type:"airline", region:"Turkey" },
  { name:"Envoy Air", type:"airline", region:"United States" },
  { name:"Rainbow Air (RAI)", type:"airline", region:"United States" },
  { name:"Rainbow Air Canada", type:"airline", region:"Canada" },
  { name:"Rainbow Air Polynesia", type:"airline", region:"United States" },
  { name:"Rainbow Air Euro", type:"airline", region:"United Kingdom" },
  { name:"Rainbow Air US", type:"airline", region:"United States" },
  { name:"Dobrolet", type:"airline", region:"Russia" },
  { name:"Spike Airlines", type:"airline", region:"United States" },
  { name:"All America", type:"airline", region:"United States" },
  { name:"All Europe", type:"airline", region:"United Kingdom" },
  { name:"All Spain", type:"airline", region:"Spain" },
  { name:"All Australia", type:"airline", region:"Australia" },
  { name:"Fly Europa", type:"airline", region:"Spain" },
  { name:"Spring Airlines Japan", type:"airline", region:"Japan" },
  { name:"Dense Airways", type:"airline", region:"United States" },
  { name:"Dense Connection", type:"airline", region:"United States" },
  { name:"Vuola Italia", type:"airline", region:"Italy" },
  { name:"Jet Suite", type:"airline", region:"United States" },
  { name:"Island Express Air", type:"airline", region:"Canada" },
  { name:"Thai Smile Airways", type:"airline", region:"Thailand" },
  { name:"SOCHI AIR EXPRESS", type:"airline", region:"Russia" },
  { name:"San Dima Air", type:"airline", region:"United States" },
  { name:"Hebradran Air Services", type:"airline", region:"United Kingdom" },
  { name:"Pobeda", type:"airline", region:"Russia" },
  { name:"City Airways", type:"airline", region:"Thailand" },
  { name:"BA101", type:"airline", region:"United Kingdom" },
  { name:"TransNusa Air", type:"airline", region:"Indonesia" },
  { name:"OneJet", type:"airline", region:"United States" },
  { name:"Air Vistara", type:"airline", region:"India" },
  { name:"TransRussiaAirlines", type:"airline", region:"Russia" },
  { name:"Severstal Air Company", type:"airline", region:"Russia" },
  { name:"REXAIR VIRTUEL", type:"airline", region:"France" },
  { name:"WestJet Encore", type:"airline", region:"Canada" },
  { name:"Air Pegasus", type:"airline", region:"India" },
  { name:"International Europe", type:"airline", region:"Spain" },
  { name:"Sky Regional Airlines", type:"airline", region:"Canada" },
  { name:"V Air", type:"airline", region:"Taiwan" },
  { name:"Cello Aviation", type:"airline", region:"United Kingdom" },
  { name:"Boutique Air (Priv)", type:"airline", region:"United States" },
  { name:"VOLOTEA Airways", type:"airline", region:"Spain" },
  { name:"Liberty Airways", type:"airline", region:"United States" },
  { name:"Аэросервис", type:"airline", region:"Russia" },
  { name:"Aeronautica Militare", type:"airline", region:"Italy" },
  { name:"Jetstar Japan", type:"airline", region:"Japan" },
  { name:"UVT Aero", type:"airline", region:"Russia" },
  { name:"First Flying", type:"airline", region:"Japan" },
  { name:"Silver Airways (3M)", type:"airline", region:"United States" },
  { name:"GermanXL", type:"airline", region:"Germany" },
  { name:"Alghanim", type:"airline", region:"United States" },
  { name:"Indonesa Air Aisa X", type:"airline", region:"Indonesia" },
  { name:"Fly France", type:"airline", region:"France" },
  { name:"Jota Aviation", type:"airline", region:"United Kingdom" },
  { name:"Europe Jet", type:"airline", region:"France" },
  { name:"Southern Airways Express", type:"airline", region:"United States" },
  { name:"Orenburzhie", type:"airline", region:"Russia" },
  { name:"World Scale Airlines", type:"airline", region:"United States" },
  { name:"All America US", type:"airline", region:"United States" },
  { name:"University of Birmingham Air Squadron (RAF)", type:"airline", region:"United Kingdom" },
  { name:"Choice Airways", type:"airline", region:"United States" },
  { name:"BudgetAir", type:"airline", region:"Germany" },
  { name:"Dynamic Airways", type:"airline", region:"United States" },
  { name:"ViaAir", type:"airline", region:"United States" },
  { name:"Thai Vietjet Air", type:"airline", region:"Thailand" },
  { name:"Jetgo Australia", type:"airline", region:"Australia" },
  { name:"Air Carnival", type:"airline", region:"India" },
  { name:"Svyaz Rossiya", type:"airline", region:"Russia" }
];
