// ==== OPERATORS ====
export const seedOperators = [
  // Chinese Railways
  { name:"中国国家铁路集团有限公司", type:"railway"},
  { name:"中国铁路北京局集团有限公司", type:"railway"},
  { name:"中国铁路上海局集团有限公司", type:"railway"},
  { name:"中国铁路广州局集团有限公司", type:"railway"},
  { name:"中国铁路成都局集团有限公司", type:"railway"},
  { name:"中国铁路武汉局集团有限公司", type:"railway"},
  { name:"中国铁路西安局集团有限公司", type:"railway"},
  { name:"中国铁路沈阳局集团有限公司", type:"railway"},
  { name:"中国铁路郑州局集团有限公司", type:"railway"},
  { name:"中国铁路济南局集团有限公司", type:"railway"},
  { name:"中国铁路南昌局集团有限公司", type:"railway"},
  { name:"中国铁路南宁局集团有限公司", type:"railway"},
  { name:"中国铁路昆明局集团有限公司", type:"railway"},
  { name:"中国铁路兰州局集团有限公司", type:"railway"},
  { name:"中国铁路哈尔滨局集团有限公司", type:"railway"},
  { name:"中国铁路太原局集团有限公司", type:"railway"},
  { name:"中国铁路呼和浩特局集团有限公司", type:"railway"},
  { name:"中国铁路乌鲁木齐局集团有限公司", type:"railway"},
  { name:"中国铁路青藏集团有限公司", type:"railway"},
  { name:"港铁公司", type:"railway"},
  { name:"台湾铁路管理局", type:"railway"},
  // Japanese Railways
  { name:"JR东日本", type:"railway"},
  { name:"JR西日本", type:"railway"},
  { name:"JR东海", type:"railway"},
  { name:"JR九州", type:"railway"},
  { name:"JR北海道", type:"railway"},
  // Korean Railways
  { name:"韩国铁道公社 (KORAIL)", type:"railway"},
  // European Railways
  { name:"SNCF (法国国家铁路)", type:"railway"},
  { name:"Deutsche Bahn (德国铁路)", type:"railway"},
  { name:"Trenitalia (意大利铁路)", type:"railway"},
  { name:"Renfe (西班牙铁路)", type:"railway"},
  { name:"Eurostar (欧洲之星)", type:"railway"},
  { name:"SBB (瑞士联邦铁路)", type:"railway"},
  { name:"NS (荷兰铁路)", type:"railway"},
  // Other Railways
  { name:"Amtrak (美国国铁)", type:"railway"},
  { name:"VIA Rail Canada", type:"railway"},
  { name:"俄罗斯铁路 (RZD)", type:"railway"},
  // Chinese Airlines
  { name:"中国国际航空 (Air China)", type:"airline"},
  { name:"中国东方航空 (China Eastern)", type:"airline"},
  { name:"中国南方航空 (China Southern)", type:"airline"},
  { name:"海南航空 (Hainan Airlines)", type:"airline"},
  { name:"深圳航空 (Shenzhen Airlines)", type:"airline"},
  { name:"厦门航空 (Xiamen Airlines)", type:"airline"},
  { name:"四川航空 (Sichuan Airlines)", type:"airline"},
  { name:"山东航空 (Shandong Airlines)", type:"airline"},
  { name:"春秋航空 (Spring Airlines)", type:"airline"},
  { name:"吉祥航空 (Juneyao Air)", type:"airline"},
  { name:"国泰航空 (Cathay Pacific)", type:"airline"},
  { name:"中华航空 (China Airlines)", type:"airline"},
  { name:"长荣航空 (EVA Air)", type:"airline"},
  // Japanese Airlines
  { name:"全日空 (ANA)", type:"airline"},
  { name:"日本航空 (JAL)", type:"airline"},
  // Korean Airlines
  { name:"大韩航空 (Korean Air)", type:"airline"},
  { name:"韩亚航空 (Asiana Airlines)", type:"airline"},
  // Southeast Asian Airlines
  { name:"新加坡航空 (Singapore Airlines)", type:"airline"},
  { name:"泰国国际航空 (Thai Airways)", type:"airline"},
  { name:"亚洲航空 (AirAsia)", type:"airline"},
  { name:"越南航空 (Vietnam Airlines)", type:"airline"},
  // Middle Eastern Airlines
  { name:"阿联酋航空 (Emirates)", type:"airline"},
  { name:"卡塔尔航空 (Qatar Airways)", type:"airline"},
  { name:"土耳其航空 (Turkish Airlines)", type:"airline"},
  // European Airlines
  { name:"汉莎航空 (Lufthansa)", type:"airline"},
  { name:"法国航空 (Air France)", type:"airline"},
  { name:"英国航空 (British Airways)", type:"airline"},
  { name:"荷兰皇家航空 (KLM)", type:"airline"},
  { name:"瑞士国际航空 (SWISS)", type:"airline"},
  // North American Airlines
  { name:"美国联合航空 (United Airlines)", type:"airline"},
  { name:"达美航空 (Delta Air Lines)", type:"airline"},
  { name:"美国航空 (American Airlines)", type:"airline"},
  { name:"加拿大航空 (Air Canada)", type:"airline"},
  // Oceanian Airlines
  { name:"澳洲航空 (Qantas)", type:"airline"},
  { name:"新西兰航空 (Air New Zealand)", type:"airline"},
  { name:"成都航空", type:"airline"},
  { name:"东海航空", type:"airline"},
  { name:"江西航空", type:"airline"},
];
